"""added relation

Revision ID: 0005
Revises: 0004
Create Date: 2025-05-29 02:12:31.710502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('telemetry_id', sa.Integer(), nullable=False), schema='trillectric')
    op.create_index(op.f('ix_trillectric_alerts_telemetry_id'), 'alerts', ['telemetry_id'], unique=False, schema='trillectric')
    op.create_foreign_key(None, 'alerts', 'telemetry', ['telemetry_id'], ['id'], source_schema='trillectric', referent_schema='trillectric')
    op.add_column('discarded', sa.Column('telemetry_id', sa.Integer(), nullable=False), schema='trillectric')
    op.create_index(op.f('ix_trillectric_discarded_telemetry_id'), 'discarded', ['telemetry_id'], unique=False, schema='trillectric')
    op.create_foreign_key(None, 'discarded', 'telemetry', ['telemetry_id'], ['id'], source_schema='trillectric', referent_schema='trillectric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discarded', schema='trillectric', type_='foreignkey')
    op.drop_index(op.f('ix_trillectric_discarded_telemetry_id'), table_name='discarded', schema='trillectric')
    op.drop_column('discarded', 'telemetry_id', schema='trillectric')
    op.drop_constraint(None, 'alerts', schema='trillectric', type_='foreignkey')
    op.drop_index(op.f('ix_trillectric_alerts_telemetry_id'), table_name='alerts', schema='trillectric')
    op.drop_column('alerts', 'telemetry_id', schema='trillectric')
    # ### end Alembic commands ###
