"""added relation

Revision ID: 0006
Revises: 0005
Create Date: 2025-05-29 02:26:03.104118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trillectric_alerts_telemetry_id'), table_name='alerts', schema='trillectric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trillectric_alerts_telemetry_id'), 'alerts', ['telemetry_id'], unique=False, schema='trillectric')
    # ### end Alembic commands ###
