"""added relation

Revision ID: 0007
Revises: 0006
Create Date: 2025-05-29 02:26:54.916742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trillectric_discarded_telemetry_id'), table_name='discarded', schema='trillectric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trillectric_discarded_telemetry_id'), 'discarded', ['telemetry_id'], unique=False, schema='trillectric')
    # ### end Alembic commands ###
