"""added relation

Revision ID: 0008
Revises: 0007
Create Date: 2025-05-29 02:29:26.835309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discarded', 'telemetry_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='trillectric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discarded', 'telemetry_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='trillectric')
    # ### end Alembic commands ###
